apiVersion: kctf.dev/v1
kind: Challenge
metadata:
  name: chal-tomcat-latest
spec:
  deployed: true
  powDifficultySeconds: 0
  network:
    public: false
    ports:
      - protocol: "TCP"
        targetPort: 8080
        port: 8080
  healthcheck:
    # TIP: disable the healthcheck during development
    enabled: false
  image: europe-west4-docker.pkg.dev/internet-ctf/challenges/challenge:aee17725fd1f01af37228551fa3144f59bc8ead305e3c2db4cd1b1aa09fd0179
